---

# Main collection of env. vars to set for all tasks and scripts.
env:
    ####
    #### Cache-image names to test with (double-quotes around names are critical)
    ####
    FEDORA_NAME: "fedora-40"
    FEDORA_AARCH64_NAME: "${FEDORA_NAME}-aarch64"

    # Image identifiers
    IMAGE_SUFFIX: "c20250401t092024z-f41f40d13"

    # EC2 images
    FEDORA_AMI: "fedora-aws-${IMAGE_SUFFIX}"
    FEDORA_AARCH64_AMI: "fedora-podman-aws-arm64-${IMAGE_SUFFIX}"
    WINDOWS_AMI: "win-server-wsl-${IMAGE_SUFFIX}"

    # Container
    FEDORA_CONTAINER_FQIN: "quay.io/acui/fedora_podman:${IMAGE_SUFFIX}"

    # directory where the images will be placed
    OUTDIR: "outdir"

    CIRRUS_WORKING_DIR: /var/tmp/podman-machine-os

    # Vars used for the macos and windows testing
    MACHINE_IMAGE_BASE_URL: "https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/image_build/image/"
    # podman version used by windows/macos verify suite
    PODMAN_INSTALL_VERSION: 5.4.1

aws_credentials: ENCRYPTED[db247afa12c49a0578e391e573dd71302df83698a66975a87996b1388473d04e52d2f50031bbf7bc0319508a1b21ba66]

# Default timeout
timeout_in: 30m

image_build_task:
    name: "Image Build ${ARCH}"
    alias: "image_build"
    ec2_instance:
        image: "${VM_IMAGE}"
        type: "${EC2_INST_TYPE}"
        region: us-east-1
        architecture: "${GO_ARCH}"
    env:
        HOME: /root
    matrix:
        - env:
            ARCH: "x86_64"
            GO_ARCH: "amd64"
            VM_IMAGE: "${FEDORA_AMI}"
            EC2_INST_TYPE: "m5zn.metal"  # Bare-metal instance is required
        - env:
            ARCH: "aarch64"
            GO_ARCH: "arm64"
            VM_IMAGE: "${FEDORA_AARCH64_AMI}"
            EC2_INST_TYPE: "c6g.metal"  # Bare-metal instance is required

    setup_script: ./contrib/cirrus/setup.sh
    build_script: ./build.sh
    image_prep_script: |
        mv $OUTDIR/*.zst .
        mv $OUTDIR/podman-machine podman-machine.${ARCH}.tar
    image_artifacts: &image_artifacts
        path: "*.{zst,tar}"
        type: application/octet-stream

image_push_task:
    name: "Image Push"
    alias: "image_push"
    # Make sure that there are not two push running at the same time.
    execution_lock: $CIRRUS_BRANCH
    # Less likely the task is canceled.
    stateful: true
    # Only push new images on tags or on commits to main
    only_if: $CIRRUS_TAG != '' || ($CIRRUS_BRANCH == 'main' && $CIRRUS_PR == "")
    depends_on:
        - image_build
    ec2_instance:
        image: "${VM_IMAGE}"
        type: "${EC2_INST_TYPE}"
        region: us-east-1
    env:
        HOME: /root
        VM_IMAGE: "${FEDORA_AMI}"
        EC2_INST_TYPE: "m5.large"
        # QUAY_USER: ENCRYPTED[53d23fbd39a3b8b0daf015edac296b56964da0b523767f79d3a8131a4871523b90c5a7554c91172c1ca0066e492853e3]
        # QUAY_PASSWORD: ENCRYPTED[3cfabb0f7fa6a36dc6af433f5a0291d87b38402c922b662e9647931a635f20ca33401aa91b29745b7af252538406a292]
        RELEASE_TOKEN: ENCRYPTED[8a65021613e50e0b499c64410c4951779169f87f35825de87f5e265e9c4722d2e36cb77cae48c59950a8eaad00e616b0]
        LABEL_TOKEN: ENCRYPTED[fee531e1a3868adb7621b5e87aa36be37aec74a065901f7e893e15d50d9111bc6dcc3ab18335e5b23ebc1d13fa05cb79]
    install_script: |
        # TODO: remove install once gh is in the image
        if [[ $CIRRUS_TAG != '' ]]; then
            sudo dnf install -y gh
        fi
    main_script: |
        mkdir $OUTDIR
        for end in applehv.raw.zst hyperv.vhdx.zst qemu.qcow2.zst tar; do
            for arch in x86_64 aarch64; do
                name="podman-machine.$arch.$end"
                curl --retry 5 --retry-delay 8 --fail --location -O --output-dir $OUTDIR --url "${MACHINE_IMAGE_BASE_URL}$name"
            done
        done

        source ./gather.sh
        podman images
        # podman login -u  "$QUAY_USER" --password-stdin quay.io <<<"$QUAY_PASSWORD"
        # time podman manifest push --all "$FULL_IMAGE_NAME"
    podman_label_script: |
        if [[ $CIRRUS_TAG != '' ]]; then
            pr=$(sed -n '/^export PODMAN_PR_NUM/s/^[^"]*"\([^"]*\)"$/\1/p' podman-rpm-info-vars.sh)
            cat podman-rpm-info-vars.sh
            echo $pr
            if [[ $pr != "" ]]; then
                gh auth login --with-token <<<"$LABEL_TOKEN"
                # gh pr edit --remove-label do-not-merge/wait-machine-os-build  https://github.com/containers/podman/pull/$pr
                gh pr edit --remove-label do-not-merge/wait-machine-os-build  https://github.com/ashley-cui/podman-actions-test/pull/15

                gh auth logout
            fi
        fi
    release_script: |
        if [[ $CIRRUS_TAG != '' ]]; then
            pushd $OUTDIR
            sha256sum * > shasums
            popd

            cat $OUTDIR

            gh auth login --with-token <<<"$RELEASE_TOKEN"

            gh release create $CIRRUS_TAG \
            -t $CIRRUS_TAG \
            --notes "$CIRRUS_TAG release images" \
            --verify-tag \
            $OUTDIR/*

            gh auth logout
        fi

# test_task:
#     name: "Total Success"
#     alias: success
#     depends_on:
#         - image_build
#         - image_push
#     container:
#         image: "${FEDORA_CONTAINER_FQIN}"
#         cpu: 1
#         memory: 1
#     noop_script: true
